### ISSUE TITLE
Ring Alarm Partition and Sensors

### ISSUE THREAD

**Issue by grabidou** [bphillips09/Control4-HA-Alarm-Panel#1]
First, THANK YOU for this integration!

is it possible to get the zones from the Ring Alarm panel and add them to C4?  or do we need to add them individually with the HA Binary Sensor driver?  Also, I added a user code to the Properties in C4, but it doesnt seem to pass through?  do we need to enter a code every time?

**Comment by bphillips09** [comment]
@grabidou Currently you'll need to add the Binary Sensors individually. I haven't added distinct Zone support to this driver yet (it's on the roadmap though!) but even when added you'll still need to connect your binary sensors individually as the entities in HA are separate (i.e. the alarm_control_panel entities don't expose select binary_sensor entities).

In the meantime, let's say you have these entities in HA:
binary_sensor.bedroom_window
binary_sensor.front_door
binary_sensor.back_door

You could add three HA Binary Sensor drivers and connect them to native Control4 "CONTACT_SENSOR" drivers like "Door Contact Sensor" and "Window Contact Sensor". This will expose them in navigators under Locks & Security.

**Comment by bphillips09** [comment]
@grabidou For the user code, the one you set in the `Security System` properties in the driver is ignored as the one in HA takes precedence. If your alarm reports to HA that `code_arm_required` is `true` (i.e. you must enter a code to Arm the alarm as well as Disarm the alarm) then the C4 driver will require that too. I can make a toggle in the driver properties to disable this but the code will still be required to disarm the alarm no matter what as that's required by HA (I think).

**Comment by grabidou** [comment]
thank you, either way I've been looking for a way to integrate an unsupported C4 alarm into C4. this works great!  have you thought of writing direct drivers from C4? not just a link between HA and C4?

**Comment by bphillips09** [comment]
> thank you, either way I've been looking for a way to integrate an unsupported C4 alarm into C4. this works great! have you thought of writing direct drivers from C4? not just a link between HA and C4?

I don't have a Ring Alarm system so I wouldn't write a driver for it specifically unless I owned one or wrote and released it as paid. It would likely be a significant undertaking since it would be comprised of many different proxy types (Alarm, Switch, Sensor, Light, etc.) and would use unofficial APIs for local control so it likely wouldn't be reliable if Ring changed the API.
